Add html page
allenkays/Mobile_Portfolio pull request #1
Opened 2023-06-07 15:15 UTC by allenkays

# html index page
In this milestone I:
- Added and index.html file and it associated images in the images directory.

2023-06-07 15:34 UTC, allenkays commented
git

2023-06-07 18:06 UTC, allenkays commented
Fixed linters errors.

2023-06-07 18:20 UTC, Bantealem reviewed
Hi @allenkays , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have README. Please make sure you used Microverse REAME template as you used for `Hello MIcroverse` Project

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-08 07:00 UTC, abdallahmalima requested changes
Hi @allenkays , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>
![](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Highlights
- Correct use of `header` tag✔
- Correct use of `nav`  tag✔
- Use flexbox✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 07:00 UTC, abdallahmalima commented on index.html
> +                    <a href="#"><img src="images/logo/logo.png" alt="menu"/></a>
- [ ] 🙏Please utilize the same color as the Figma design hamburger menu to match the Figma design. This will enhance the appearance🌹 of your app and give it a cool look🤩, just like the Figma design.

Your design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/eb8148bd-3fb9-4651-becf-345d6e2c8caa)

Figma design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/0632cd71-b244-46ba-9158-54ae98854fa4)

- [ ] 🙏 Please adjust the left and right padding of your navigation to match the spacing of the Figma design. This will enhance the appearance🌹 of your app and give it a cool look🤩, just like the Figma design.

Your design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/eb8148bd-3fb9-4651-becf-345d6e2c8caa)

Figma design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/fbdbf2df-f3c6-49c2-a644-8b2aabcd69c7)

2023-06-08 07:00 UTC, abdallahmalima commented on index.html
> +                </article>
- [ ] 🙏Please modify the margins of this tag to align with the Figma design. This will enhance the appearance🌹 of your app and give it a cool look🤩, just like the Figma design.

Your design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/2086bfe0-28a4-4d53-ab6a-7919182b827f)

Figma design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/ae314e71-982d-435f-be9c-751f84d16e15)

2023-06-08 07:00 UTC, abdallahmalima commented on index.html
> +                    <a href="https://medium.com/@allainkibet"><img  id="profile" src="images/contact_profiles/medium.svg"/></a>
- [ ] 🙏Please utilize the same color as the Figma design icons to ensure consistency with the Figma design. This will enhance the appearance🌹 of your app and give it a cool look🤩, just like the Figma design.
- [ ] 🙏Please modify the margins of the icons to align with the Figma design.

Your design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/0ff4747b-ab15-4b66-ac93-b7383582b593)

Figma design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/84adf28e-403f-45c0-a602-e502f55ba28c)

2023-06-08 07:00 UTC, abdallahmalima commented on index.html
> +                    <h1 class="main-title">Hey There. I’m Allan.</h1>
- [ ] 🙏Please include the background image as per the Figma design. This will enhance the overall appearance😍 of the design and maintain consistency with the Figma design.

Your design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/7addc4e3-c7e5-47f8-b897-18ef91dd171e)

Figma design:
![image](https://github.com/allenkays/Mobile_Portfolio/assets/63445083/365ec149-0a55-44c4-af54-9fd323728d3b)

2023-06-08 07:00 UTC, abdallahmalima commented on index.html
> +                    <a href="https://www.linkedin.com/in/allan-sang/"><img  id="profile" src="images/contact_profiles/linkedIn.svg"/></a>
- [ ] 🙏Please wrap these icons' links with a `<li>` (list item) tag. This is a project requirement and provides a better👍 semantic structure to the code.
```suggestion
<ul>
     <li>
          <a href="https://github.com/allenkays"><img  id="profile" src="images/contact_profiles/github.svg"/> </a>
      </li>
       <li>
           <a href="https://www.linkedin.com/in/allan-sang/">
           <img  id="profile" src="images/contact_profiles/linkedIn.svg"/></a>
        </li>
 </ul>
```

2023-06-08 20:01 UTC, frank1738 approved these changes
Hi @allenkays , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/tIeCLkB8geYtW/giphy.gif"/>

## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ Good design

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 20:49 UTC, merged